FROM rabbitmq:3.8-management-alpine

# Expose ports for RabbitMQ and management UI
EXPOSE 5672 15672

# Define volumes for data and logs
VOLUME ["/var/lib/rabbitmq/", "/var/log/rabbitmq/"]

COPY rabbitmq.conf /etc/rabbitmq/

ENV RABBITMQ_NODENAME=rabbit@localhost

RUN chown rabbitmq:rabbitmq /etc/rabbitmq/rabbitmq.conf

USER rabbitmq:rabbitmq